#=========================================================#
# Monitor Layout DP-1 left (4k), HDMI-A-1 right (1080p)
#=========================================================#
# Logical layout: 4K (Scale 2) starts at 0,0. 1080p starts at 1920,0.
monitorrule=name:DP-1,width:3840,height:2160,refresh:60,x:0,y:0,scale:2
monitorrule=name:HDMI-A-1,width:1920,height:1080,refresh:60,x:1920,y:0,scale:1

